/***********************************************************************/
/*  													               */
/*      PROJECT NAME :  FourAxisControl                                */
/*      FILE         :  FourAxisControl.c                              */
/*      DESCRIPTION  :  Main Program                                   */
/*      CPU SERIES   :  RX600                                          */
/*      CPU TYPE     :  RX62N                                          */
/*  													               */
/*      This file is generated by KPIT Eclipse.                        */
/*  													               */
/***********************************************************************/                                                                        
#include "Global.h"
extern void BlinkRunLED(void);

void main(void)
{
	OUTEN = 1;
	PressValve = 1;
	
	Enableb485Rx();
	ServoInit();
	InitVariable();	
	ServoSpeedInit();
	while(1)
	{	
		ReadInput();
		CalGearRatio();
		//ServoDrvProct();
		//TestOutput();
		Action();
		WriteOutput();
		CheckReceData();
		BlinkRunLED();
	}
}



